AWSTemplateFormatVersion: '2010-09-09'

Description: S3 Bucket that holds released SAM Applications.

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "serverlessrepo.amazonaws.com"
            Action: "s3:GetObject"
            Resource: !Sub "${S3Bucket.Arn}/*"
            Condition:
              StringEquals:
                "aws:SourceAccount": !Ref AWS::AccountId

Outputs:
  BucketArn:
    Description: ARN of the S3 Bucket that holds released SAM Applications.
    Value: !GetAtt S3Bucket.Arn

  BucketName:
    Description: Name of the S3 Bucket that holds released SAM Applications.
    Value: !Ref S3Bucket
